project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  scripts: scripts
  tests: tests

networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      host: http://127.0.0.1:7545/
      port: 7545
  live:
    gas_limit: auto
    gas_buffer: 1.1
    gas_price: auto
    reverting_tx_gas_limit: false
    default_contract_owner: false
  rinkeby:
    host: https://rinkeby.infura.io/v3/9d9db26b6f8f47f5b3f2e04c8ca9f9fa
    explorer: https://api-rinkeby.etherscan.io/api
  rospten:
    host: https://ropsten.infura.io/v3/9d9db26b6f8f47f5b3f2e04c8ca9f9fa

compiler:
  evm_version: null
  solc:
    version: 0.6.6
    optimizer:
      enabled: true
      runs: 200
    remappings: null
  vyper:
    version: null

console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs

reports:
  exclude_paths: null
  exclude_contracts: null

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

autofetch_sources: True
dependencies: null
dev_deployment_artifacts: false

wallets:
  from_key: PRIVATE_KEY
